pipeline.yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -1,8 +1,6 @@
-name: Automation - Python>>>Behave>>>Pytest 
+name: Automation - Python>>>Behave>>>Pytest
 
 on:
-  repository_dispatch:
-    types: [trigger-from-stage]
   workflow_dispatch:
 
 jobs:
@@ -21,22 +19,22 @@ jobs:
       - name: Instalar dependências
         run: |
           python -m pip install --upgrade pip
-          pip install behave behave-html-formatter
-          pip install selenium
-          pip install faker
-          pip install webdriver-manager
+          pip install behave behave-html-formatter selenium faker webdriver-manager
 
-      - name: Rodar os testes com Behave + gerar relatório HTML
+      - name: Rodar testes com Behave + gerar relatório
+        id: run_tests
         run: |
           cd aut_front
           mkdir -p reports
-          behave -f behave_html_formatter:HTMLFormatter -o reports/behave_report.html
+          behave -f behave_html_formatter:HTMLFormatter -o reports/behave_report.html || echo "tests_failed=true" >> $GITHUB_ENV
 
-      - name: Upload do relatório HTML como artefato
-        uses: actions/upload-artifact@v4
-        with:
-          name: Relatorio-Behave
-          path: aut_front/reports/behave_report.html
+      - name: Criar corpo do e-mail dinamicamente
+        run: |
+          if [[ "${{ env.tests_failed }}" == "true" ]]; then
+            echo "📊 Relatório de Testes Automatizados - Behave  \nHouveram ❌ FALHAS ❌ nos testes automatizados.\nConfira os detalhes no relatório em anexo." > email_body.txt
+          else
+            echo "📊 Relatório de Testes Automatizados - Behave  \nTodos os testes passaram com sucesso! ✅\nRelatório em anexo." > email_body.txt
+          fi
 
       - name: Enviar relatório por e-mail
         uses: dawidd6/action-send-mail@v3
@@ -45,20 +43,18 @@ jobs:
           server_port: 465
           username: ${{ secrets.EMAIL_USERNAME }}
           password: ${{ secrets.EMAIL_PASSWORD }}
-          subject: BBVA Relatório de Testes Automatizados
+          subject: Relatório de Testes Automatizados - Behave
           to: silvio.aulik@gmail.com
           cc: staulik10@gmail.com, qatadeu@gmail.com
           from: ${{ secrets.EMAIL_USERNAME }}
           secure: true
-          content_type: text/html
-          body: |
-            📊 Relatório de Testes Automatizados - BBVA  
-            Segue em anexo o relatório da última execução dos testes.  
-            Status: **Sucesso**
+          content_type: text/plain
+          body: file://email_body.txt
           attachments: aut_front/reports/behave_report.html
 
-      - name: Mensagem de encerramento
-        run: echo "✅ Workflow finalizado. Relatório enviado por e-mail com sucesso!"
+      - name: Finalização
+        run: echo "✅ Workflow encerrado. E-mail enviado com base no status da execução!"
+
 
 
 
